/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-01 12:02:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"robots\" content=\"all,follow\">\r\n");
      out.write("    <meta name=\"googlebot\" content=\"index,follow,snippet,archive\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"Obaju e-commerce template\">\r\n");
      out.write("    <meta name=\"author\" content=\"Ondrej Svestka | ondrejsvestka.cz\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>\r\n");
      out.write("        MedioxyPharm\r\n");
      out.write("    </title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"keywords\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>\r\n");
      out.write("\r\n");
      out.write("    <!-- styles -->\r\n");
      out.write("    <link href=\"css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"css/owl.theme.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- theme stylesheet -->\r\n");
      out.write("    <link href=\"css/style.default.css\" rel=\"stylesheet\" id=\"theme-stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- your stylesheet with modifications -->\r\n");
      out.write("    <link href=\"css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"js/respond.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.png\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- *** TOPBAR ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("    <div id=\"top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"col-md-6 offer\" data-animate=\"fadeInDown\">\r\n");
      out.write("                <a href=\"#\" class=\"btn btn-success btn-sm\" data-animate-hover=\"shake\">Offer of the day</a>  <a href=\"#\">Get flat 35% off on orders over $50!</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\" data-animate=\"fadeInDown\">\r\n");
      out.write("                <ul class=\"menu\">\r\n");
      out.write("                    <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#login-modal\">Login</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"register.jsp\">Register</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"contact.jsp\">Contact</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">Recently viewed</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal fade\" id=\"login-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"Login\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                        <h4 class=\"modal-title\" id=\"Login\">Customer login</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <form action=\"customer-orders.html\" method=\"post\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"email-modal\" placeholder=\"email\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"password-modal\" placeholder=\"password\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <p class=\"text-center\">\r\n");
      out.write("                                <button class=\"btn btn-primary\"><i class=\"fa fa-sign-in\"></i> Log in</button>\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"text-center text-muted\">Not registered yet?</p>\r\n");
      out.write("                        <p class=\"text-center text-muted\"><a href=\"register.jsp\"><strong>Register now</strong></a></p>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- *** TOP BAR END *** -->\r\n");
      out.write("    \r\n");
      out.write("        <!-- *** NAVBAR ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"navbar navbar-default yamm\" role=\"navigation\" id=\"navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"navbar-header\">\r\n");
      out.write("\r\n");
      out.write("                <a class=\"navbar-brand home\" href=\"index.jsp\" data-animate-hover=\"bounce\">\r\n");
      out.write("                    <img src=\"img/logo.jpg\" alt=\"logo\" class=\"hidden-xs\">\r\n");
      out.write("                    <img src=\"img/logo-small.jpg\" alt=\"logo\" class=\"visible-xs\"><span class=\"sr-only\"></span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"navbar-buttons\">\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navigation\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                        <i class=\"fa fa-align-justify\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#search\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle search</span>\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <a class=\"btn btn-default navbar-toggle\" href=\"basket.html\">\r\n");
      out.write("                        <i class=\"fa fa-shopping-cart\"></i>  <span class=\"hidden-xs\">3 items in cart</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.navbar-header -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-collapse collapse\" id=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"nav navbar-nav navbar-left\">\r\n");
      out.write("                    <li class=\"active\"><a href=\"index.html\">Home</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">OTC<b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"yamm-content\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"\">\r\n");
      out.write("                                            <!-- <h5>Clothing</h5> -->\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><a href=\"category.html\">First Aid</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Health Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Mens Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Womens Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!--  -->\r\n");
      out.write("                                        \r\n");
      out.write("                                <!-- /.yamm-content -->\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">BABY & MOTHER <b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"yamm-content\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><a href=\"category.html\">Baby & Infant</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Maternity & Mother Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                <!-- /.yamm-content -->\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">PERSONAL CARE <b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"yamm-content\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><a href=\"category.html\">Body Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Eye Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Hair Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Facial Kit</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Mens Essentials</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Womens Essentials</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                <!-- /.yamm-content -->\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">WELLNESS <b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"yamm-content\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><a href=\"category.html\">Fitness</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Health Drinks</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Supplements</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                <!-- /.yamm-content -->\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">MEDICAL EQUIPMENTS & SUPPORT  <b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"yamm-content\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><a href=\"category.html\">Medical Instruments</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Ortho Support</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Senior Care</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                <!-- /.yamm-content -->\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("                    <li class=\"dropdown yamm-fw\">\r\n");
      out.write("                        <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-hover=\"dropdown\" data-delay=\"200\">EXPERT ADVICE  <b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <div class=\"yamm-content\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"\">\r\n");
      out.write("                                            \r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <li><a href=\"category.html\">Advice For Seniors</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Advice For Juniors</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li><a href=\"category.html\">Child Therapy</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                                <!-- /.yamm-content -->\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                                        \r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.nav-collapse -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navbar-buttons\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"navbar-collapse collapse right\" id=\"basket-overview\">\r\n");
      out.write("                    <a href=\"basket.html\" class=\"btn btn-primary navbar-btn\"><i class=\"fa fa-shopping-cart\"></i><span class=\"hidden-sm\">3 items in cart</span></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--/.nav-collapse -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"navbar-collapse collapse right\" id=\"search-not-mobile\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn navbar-btn btn-primary\" data-toggle=\"collapse\" data-target=\"#search\">\r\n");
      out.write("                        <span class=\"sr-only\">Toggle search</span>\r\n");
      out.write("                        <i class=\"fa fa-search\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"collapse clearfix\" id=\"search\">\r\n");
      out.write("\r\n");
      out.write("                <form class=\"navbar-form\" role=\"search\">\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search\">\r\n");
      out.write("                        <span class=\"input-group-btn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("\r\n");
      out.write("\t\t    </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--/.nav-collapse -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.container -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#navbar -->\r\n");
      out.write("\r\n");
      out.write("    <!-- *** NAVBAR END *** -->\r\n");
      out.write("    \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
