/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-01 22:12:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("        <!-- *** FOOTER ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("        <div id=\"footer\" data-animate=\"fadeInUp\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                        <h4>Pages</h4>\r\n");
      out.write("\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"text.html\">About us</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"text.html\">Terms and conditions</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"faq.html\">FAQ</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"contact.jsp\">Contact us</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"hidden-md hidden-lg\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("                        <h4>Where to find us</h4>\r\n");
      out.write("\r\n");
      out.write("                        <p><strong>Obaju Ltd.</strong>\r\n");
      out.write("                            <br>13/25 New Avenue\r\n");
      out.write("                            <br>New Heaven\r\n");
      out.write("                            <br>45Y 73J\r\n");
      out.write("                            <br>England\r\n");
      out.write("                            <br>\r\n");
      out.write("                            <strong>Great Britain</strong>\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <a href=\"contact.jsp\">Go to contact page</a>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"hidden-md hidden-lg\">\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("                        <h4>Get the news</h4>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"text-muted\">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>\r\n");
      out.write("\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\">\r\n");
      out.write("\r\n");
      out.write("                                <span class=\"input-group-btn\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t    <button class=\"btn btn-default\" type=\"button\">Subscribe!</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /input-group -->\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        <hr>\r\n");
      out.write("\r\n");
      out.write("                        <h4>Stay in touch</h4>\r\n");
      out.write("\r\n");
      out.write("                        <p class=\"social\">\r\n");
      out.write("                            <a href=\"#\" class=\"facebook external\" data-animate-hover=\"shake\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                            <a href=\"#\" class=\"twitter external\" data-animate-hover=\"shake\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("                            <a href=\"#\" class=\"instagram external\" data-animate-hover=\"shake\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                            <a href=\"#\" class=\"gplus external\" data-animate-hover=\"shake\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("                            <a href=\"#\" class=\"email external\" data-animate-hover=\"shake\"><i class=\"fa fa-envelope\"></i></a>\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.col-md-3 -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#footer -->\r\n");
      out.write("\r\n");
      out.write("        <!-- *** FOOTER END *** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- *** COPYRIGHT ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("        <div id=\"copyright\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <p class=\"pull-left\">© 2015 Your name goes here.</p>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6\">\r\n");
      out.write("                    <p class=\"pull-right\">Template by <a href=\"https://bootstrapious.com/e-commerce-templates\">Bootstrapious</a> & <a href=\"https://fity.cz\">Fity</a>\r\n");
      out.write("                         <!-- Not removing these links is part of the license conditions of the template. Thanks for understanding :) If you want to use the template without the attribution links, you can do so after supporting further themes development at https://bootstrapious.com/donate  -->\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- *** COPYRIGHT END *** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#all -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- *** SCRIPTS TO INCLUDE ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("    <script src=\"js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"js/jquery.cookie.js\"></script>\r\n");
      out.write("    <script src=\"js/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"js/modernizr.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap-hover-dropdown.js\"></script>\r\n");
      out.write("    <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"js/front.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
