/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M26
 * Generated at: 2017-10-01 22:12:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"all\">\r\n");
      out.write("\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div id=\"main-slider\">\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img src=\"img/img2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img class=\"img-responsive\" src=\"img/img1.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img class=\"img-responsive\" src=\"img/img4.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <img class=\"img-responsive\" src=\"img/img3.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /#main-slider -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- *** ADVANTAGES HOMEPAGE ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("            <div id=\"advantages\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"same-height-row\">\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"box same-height clickable\">\r\n");
      out.write("                                <div class=\"icon\"><i class=\"fa fa-heart\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <h3><a href=\"#\">We love our customers</a></h3>\r\n");
      out.write("                                <p>We are known to provide best possible service ever</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"box same-height clickable\">\r\n");
      out.write("                                <div class=\"icon\"><i class=\"fa fa-tags\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <h3><a href=\"#\">Best prices</a></h3>\r\n");
      out.write("                                <p>We provide products to our customers at best price.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-sm-4\">\r\n");
      out.write("                            <div class=\"box same-height clickable\">\r\n");
      out.write("                                <div class=\"icon\"><i class=\"fa fa-thumbs-up\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <h3><a href=\"#\">100% satisfaction guaranteed</a></h3>\r\n");
      out.write("                                <p>Free returns on everything for 3 months.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /#advantages -->\r\n");
      out.write("\r\n");
      out.write("            <!-- *** ADVANTAGES END *** -->\r\n");
      out.write("\r\n");
      out.write("            <!-- *** HOT PRODUCT SLIDESHOW ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write(" \r\n");
      out.write(" <br>\r\n");
      out.write("            <div id=\"hot\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"col-md-12\">\r\n");
      out.write("                            <h2>Top Selling Products</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"product-slider\">\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product1.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product1_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product1.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">Fur coat with very but very very long name</a></h3>\r\n");
      out.write("                                    <p class=\"price\">$143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product2_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">White Blouse Armani</a></h3>\r\n");
      out.write("                                    <p class=\"price\"><del>$280</del> $143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon sale\">\r\n");
      out.write("                                    <div class=\"theribbon\">SALE</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon new\">\r\n");
      out.write("                                    <div class=\"theribbon\">NEW</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon gift\">\r\n");
      out.write("                                    <div class=\"theribbon\">GIFT</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product3_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">Black Blouse Versace</a></h3>\r\n");
      out.write("                                    <p class=\"price\">$143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product3_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">Black Blouse Versace</a></h3>\r\n");
      out.write("                                    <p class=\"price\">$143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product2_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">White Blouse Versace</a></h3>\r\n");
      out.write("                                    <p class=\"price\">$143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon new\">\r\n");
      out.write("                                    <div class=\"theribbon\">NEW</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product1.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product1_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product1.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">Fur coat</a></h3>\r\n");
      out.write("                                    <p class=\"price\">$143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon gift\">\r\n");
      out.write("                                    <div class=\"theribbon\">GIFT</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- /.col-md-4 -->\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product2_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">White Blouse Armani</a></h3>\r\n");
      out.write("                                    <p class=\"price\"><del>$280</del> $143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon sale\">\r\n");
      out.write("                                    <div class=\"theribbon\">SALE</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon new\">\r\n");
      out.write("                                    <div class=\"theribbon\">NEW</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"ribbon gift\">\r\n");
      out.write("                                    <div class=\"theribbon\">GIFT</div>\r\n");
      out.write("                                    <div class=\"ribbon-background\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.ribbon -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"item\">\r\n");
      out.write("                            <div class=\"product\">\r\n");
      out.write("                                <div class=\"flip-container\">\r\n");
      out.write("                                    <div class=\"flipper\">\r\n");
      out.write("                                        <div class=\"front\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"back\">\r\n");
      out.write("                                            <a href=\"detail.html\">\r\n");
      out.write("                                                <img src=\"img/product3_2.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"detail.html\" class=\"invisible\">\r\n");
      out.write("                                    <img src=\"img/product3.jpg\" alt=\"\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"text\">\r\n");
      out.write("                                    <h3><a href=\"detail.html\">Black Blouse Versace</a></h3>\r\n");
      out.write("                                    <p class=\"price\">$143.00</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- /.text -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- /.product -->\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /.product-slider -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /#hot -->\r\n");
      out.write("\r\n");
      out.write("            <!-- *** HOT END *** -->\r\n");
      out.write("\r\n");
      out.write("            <!-- *** GET INSPIRED ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("            <div class=\"container\" data-animate=\"fadeInUpBig\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <div class=\"box slideshow\">\r\n");
      out.write("                        <h3><span style:\"color=blue\">Our World Class Medicines</span></h3>\r\n");
      out.write("                        \r\n");
      out.write("                        <div id=\"get-inspired\" class=\"owl-carousel owl-theme\">\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"img/med1.jpeg\" alt=\"Get inspired\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"img/med4.jpeg\" alt=\"Get inspired\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"img/med2.jpeg\" alt=\"Get inspired\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"img/med3.jpeg\" alt=\"Get inspired\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"item\">\r\n");
      out.write("                                <a href=\"#\">\r\n");
      out.write("                                    <img src=\"img/med5.jpeg\" alt=\"Get inspired\" class=\"img-responsive\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- *** GET INSPIRED END *** -->\r\n");
      out.write("\r\n");
      out.write("            <!-- *** BLOG HOMEPAGE ***\r\n");
      out.write(" _________________________________________________________ -->\r\n");
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-12\" data-animate=\"fadeInUp\">\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"blog-homepage\" class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <div class=\"post\">\r\n");
      out.write("                                <h4><a href=\"post.html\">Shop now</a></h4>\r\n");
      out.write("                                <p class=\"author-category\">By <a href=\"#\">John Slim</a> in <a href=\"\">Fashion and style</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <p class=\"intro\">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean\r\n");
      out.write("                                    ultricies mi vitae est. Mauris placerat eleifend leo.</p>\r\n");
      out.write("                                <p class=\"read-more\"><a href=\"post.html\" class=\"btn btn-primary\">Continue reading</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-sm-6\">\r\n");
      out.write("                            <div class=\"post\">\r\n");
      out.write("                                <h4><a href=\"post.html\">Best Medicine</a></h4>\r\n");
      out.write("                                <p class=\"author-category\">By <a href=\"#\">John Slim</a> in <a href=\"\">About Minimal</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <hr>\r\n");
      out.write("                                <p class=\"intro\">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean\r\n");
      out.write("                                    ultricies mi vitae est. Mauris placerat eleifend leo.</p>\r\n");
      out.write("                                <p class=\"read-more\"><a href=\"post.html\" class=\"btn btn-primary\">Continue reading</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- /#blog-homepage -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("            <!-- *** BLOG HOMEPAGE END *** -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /#content -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
